apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: ubuntu
    name: test-container
    volumeMounts:
    - mountPath: /var/log/nginx
      name: vol-test
  volumes:
  - name: vol-test
    emptyDir: {}