apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  annotations:
    kubernetes.io/change-cause: cambio de imagen alpine
  labels:
    app: backend
spec:
  replicas: 50
  selector:
    matchLabels:
      app: podbackend
  template:
    metadata:
      labels:
        app: podbackend
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
  namespace: default
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 80
  - name: https
    port: 8081
    targetPort: 443
  selector:
    app: podbackend