apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  annotations:
    kubernetes.io/change-cause: cambio de imagen mysql
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podbackend
  template:
    metadata:
      labels:
        app: podbackend
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: svc-mysql
  namespace: default
spec:
  type: NodePort
  ports:
  - name: mysql
    port: 8080
    targetPort: 3306
  selector:
    app: podbackend