apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/hugosite"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hugo-app
  labels:
    app: hugo-app
spec:
  replicas: 1
  selector:
    matchLabels:
        app: hugo-app
  template:
    metadata:
      labels:
        app: hugo-app
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
        - name: hugo-app
          image: ubuntu:hugo
          volumeMounts:
            - mountPath: "/root/hugosite"
              name: task-pv-storage
---
# svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: hugo-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 30000
      targetPort: 30000
      nodePort: 30000