apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  annotations:
    kubernetes.io/change-cause: cambio de imagen mysql
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podbackend
  template:
    metadata:
      labels:
        app: podbackend
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
        - name: MYSQL_DATABASE
          value: my_wiki
        - name: MYSQL_USER
          value: wikiuser
        - name: MYSQL_PASSWORD
          value: example
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: svc-mysql
  namespace: default
spec:
  type: ClusterIP
  ports:
  - name: mysqlport
    port: 3306
    targetPort: 3306
  selector:
    app: podbackend