apiVersion: v1
kind: Pod
metadata:
  name: doscont
  namespace: default
  labels:
    app: doscont
spec:
  containers:
    - name: nginx
      image: nginx:alpine
    - name: busybox
      image: busybox
      command:
      - sleep
      - "3600"