apiVersion: v1
kind: Pod
metadata:
  name: servidor3
  namespace: default
  labels:
    produccion: nginx-des
  # etiqueta 1
spec:
  containers:
    - image:  httpd
      name:  apache1
---
apiVersion: v1
kind: Pod
metadata:
  name: servidor4
  namespace: default
  labels:
    app: nginx
spec:
  containers:
    - image:  nginx:alpine
      name:  nginx