apiVersion: v1
kind: Pod
metadata:
  name: web1
  namespace: default
  labels:
    app: web1
spec:
  containers:
    - name: nginx1
      image: nginx
      ports:
      - containerPort: 80
    - name: nginx2
      image: nginx
      ports:
      - containerPort: 81