apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediaw-pv1
  labels:
    mediaw: ready
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mediawiki"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediaw-pvc1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector: 
    matchLabels: 
      mediaw: ready
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-mediawiki
  labels:
    app: mediawiki
spec:
  revisionHistoryLimit: 15
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: mediawiki
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
      - image: mediawiki:latest
        name: contenedor-wiki
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
          - mountPath: "/var/www/html/"
            name: vol-mediaw
      volumes:
        - name: vol-mediaw
          persistentVolumeClaim:
            claimName: mediaw-pvc1
---
apiVersion: v1
kind: Service
metadata:
  name: mediawiki
  namespace: default
spec:
  type: NodePort
  ports:
  - name: http
    port: 8090
    targetPort: 80
  selector:
    app: mediawiki