apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-mediawiki
  labels:
    app: mediawiki
spec:
  revisionHistoryLimit: 15
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: mediawiki
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
      - image: mediawiki:latest
        name: contenedor-wiki
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mediawiki
  namespace: default
spec:
  type: NodePort
  ports:
  - name: http
    port: 8090
    targetPort: 80
  selector:
    app: mediawiki