apiVersion: v1
items:
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"ReplicaSet","metadata":{"annotations":{},"name":"replica1","namespace":"default"},"spec":{"replicas":10,"selector":{"matchLabels":{"repli1":"copias1"}},"template":{"metadata":{"labels":{"repli1":"copias1"}},"spec":{"containers":[{"image":"httpd","name":"servidorweb"}]}}}}
    creationTimestamp: "2023-09-14T01:07:02Z"
    generation: 3
    name: replica1
    namespace: default
    resourceVersion: "11227"
    uid: d8aad5f7-396c-4b1e-b6ef-c6f9162a1e12
  spec:
    replicas: 10
    selector:
      matchLabels:
        repli1: copias1
    template:
      metadata:
        creationTimestamp: null
        labels:
          repli1: copias1
      spec:
        containers:
        - image: httpd
          imagePullPolicy: Always
          name: servidorweb
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 10
    fullyLabeledReplicas: 10
    observedGeneration: 3
    readyReplicas: 10
    replicas: 10
kind: List
metadata:
  resourceVersion: ""
