apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica1
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      stage: produccion
  template:
    metadata:
      labels:
        stage: produccion
    spec:
      containers:
        - image: nginx:alpine
          name:  servidorweb