apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica1
  namespace: default
spec:
  replicas: 10
  selector:
    matchLabels:
      repli1: copias1
  template:
    metadata:
      labels:
        repli1: copias1
    spec:
      containers:
        - image: httpd
          name:  servidorweb