apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica1
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: copias1
  template:
    metadata:
      labels:
        app: copias1
    spec:
      containers:
        - image:  nginx:alpine
          name:  servidorweb